### ISSUE TITLE
CLI does not support file paths with spaces

### ISSUE THREAD

**Issue by kaspersorensen** [datacleaner/DataCleaner#1375] opened 2016-06-01 04:23 UTC
I wanted to make a demo for my [DataCleaner docker repo](https://github.com/kaspersorensen/datacleaner-docker) but unfortunately ran into a problem with demonstrating the command-line invocation of the example jobs: They contain spaces, and the CLI seems to fail to handle file paths with spaces.

For example (this example is on Mac, not Docker):
```
> /Applications/DataCleaner/datacleaner.sh -job /Users/kasper/.datacleaner/5.0.2/jobs/Customer profiling.analysis.xml
[...]
java.lang.IllegalStateException: java.io.FileNotFoundException: /Users/kasper/.datacleaner/5.0.2/jobs/Customer (No such file or directory)
```
Quite obviously from the exception, the argument parsing is stopping after "Customer" because of the space. I also tried with `%20` and `\ ` to escape the space, but still without luck.

**Comment by LosD** [comment] 2016-06-01 06:54
Seems to work fine, as long as you use "" around the filename, at least on Windows. Isn't that pretty much expected behavior?

**Comment by LosD** [comment] 2016-06-01 13:47
Space escaping also seems to work perfectly in mingw bash: `./DataCleaner-console.exe -conf ~/.datacleaner/5.0.3/conf.xml -job ~/.datacleaner/5.0.3/jobs/Customer\ filtering.analysis.xml`

It is also somehow weird if it doesn't... Escaping and separating arguments is the shell's responsibility, not the programs'.

@jhorcicka Could I get you to test if your Linux installation has similar problems to @kaspersorensen?

**Comment by LosD** [comment] 2016-06-01 13:49
Of course, it could be an issue in the shell script and passing the arguments properly.

**Comment by LosD** [comment] 2016-06-01 13:54
Yeah, I think the problem is here:
`exec java $DATACLEANER_JAVA_OPTS -jar $DATACLEANER_LIB_HOME/DataCleaner.jar $*`

That `$*` should probably have been a `$@`, which quotes the arguments when passing them on.

**Comment by kaspersorensen** [comment] 2016-09-19 15:49
This is still an issue in DC 5.1.3 - at least via the docker image: https://hub.docker.com/r/kaspersor/datacleaner/

**Comment by LosD** [comment] 2016-09-19 19:51
Fixed in community shellscript, PR raised for shellscript for commercial edition

**Comment by LosD** [comment] 2016-09-19 20:30
This will BTW still not work with the reported command, you will need to quote the file or escape the space, but that is expected behavior for almost all shell commands. This should work:
`/Applications/DataCleaner/datacleaner.sh -job "/Users/kasper/.datacleaner/5.0.2/jobs/Customer profiling.analysis.xml"`

**Closed** 2016-09-22 07:29 UTC
Labels: Component: Desktop, Type: Bug
