### ISSUE TITLE
New CSV datastore: new file selection; problem with different number of columns

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1496] opened 2016-09-08 10:50 UTC
1) Open a new fixed-width datastore dialog. 
2) Select a file with N columns. 
3) Select another file with M columns (N != M). 
4) Save datastore. 
5) Start a job with this datastore. 
6) Preview data. 
7) Get error. 

![naming-1](https://cloud.githubusercontent.com/assets/13213915/18346856/c88b4a1e-75c2-11e6-8ccb-9309623c0dce.png)
![naming-2](https://cloud.githubusercontent.com/assets/13213915/18346855/c88a97a4-75c2-11e6-976c-61f2140dd022.png)
![naming-3](https://cloud.githubusercontent.com/assets/13213915/18346854/c88a6838-75c2-11e6-8944-5a64e4e187f8.png)

```
ERROR 12:38:55 DataSetWindow - Unexpected error occurred while building DataSetWindow contents
org.apache.metamodel.csv.InconsistentRowLengthException: Inconsistent length of row no. 1. Expected 16 columns but found 24.
	at org.apache.metamodel.csv.SingleLineCsvRow.getValuesInternal(SingleLineCsvRow.java:69)
	at org.apache.metamodel.csv.SingleLineCsvRow.getValue(SingleLineCsvRow.java:122)
	at org.apache.metamodel.data.DataSetTableModel.getValueAt(DataSetTableModel.java:97)
	at org.datacleaner.windows.DataSetWindow.touchTableModel(DataSetWindow.java:207)
	at org.datacleaner.windows.DataSetWindow.access$200(DataSetWindow.java:60)
	at org.datacleaner.windows.DataSetWindow$2.doInBackground(DataSetWindow.java:158)
	at org.datacleaner.windows.DataSetWindow$2.doInBackground(DataSetWindow.java:155)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ClaudiaPHI** [comment] 2016-09-08 12:30
This issue does't appear with https://github.com/datacleaner/DataCleaner/pull/1487

**Comment by ClaudiaPHI** [comment] 2016-09-08 12:50
I am closing this because this is not a bug, it's a feature. The reading of file fails if the row's columns size vary in size and in the csv configuration dialog the user has chosen to fail if the rows are not consistent in size.

**Closed by ClaudiaPHI** 2016-09-08 12:50 UTC
Labels: Component: Desktop, Type: Bug
