### ISSUE TITLE
The Remove Directory component only remove the first match found.

### ISSUE THREAD

**Issue by chubbard16** [datacleaner/DataCleaner#1124] opened 2016-02-05 10:47 UTC
If remove directory uses a list of values that contains variation of the same word or phrase, it will only remove the first matched string.

For example, if a directory list contains 

- No
- Data
- No Data 

And the column contained "**No Data**" only the "**No**" would be removed, which is not the desired result.

**Comment by LosD** [comment] 2016-02-05 12:06
Duplicate of #1116

**Closed by LosD** 2016-02-05 12:06 UTC
