### ISSUE TITLE
Multiple input columns in "Value distribution" component

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1030] opened 2015-12-23 14:28 UTC
#### Description
A workflow with some input, transformer (e. g. Concatenator) and a value distribution. When multiple input columns for value distribution are selected, no change in GUI is performed (no more value distribution components, no more links). After loading (previously saved) job there is a value distribution component for each column (with proper link). 

##### Before save
![beforesave](https://cloud.githubusercontent.com/assets/13213915/11978174/ad84c872-a989-11e5-8f2e-0e4cdf60fecb.png)

##### After load
![afterload](https://cloud.githubusercontent.com/assets/13213915/11978176/b0dd02be-a989-11e5-86a6-8439e094cfbb.png)

#### Expected behavior
1) Multiple value distribution components are created right after the selection of more input columns. 
[Or. 2) There is only one distribution component with multiple links in the workflow. ]

**Comment by kaspersorensen** [comment] 2015-12-23 15:01
I think this is a duplicate of #412 
But since your description is actually more accurate, maybe we should rather let this one survive and close the other one?.

**Comment by jhorcicka** [comment] 2015-12-26 17:00
OK, but then I'd like to have your comment here. @kaspersorensen said: 

Thanks for this bug report. I have confirmed it and can also shed a bit of technicality light over it:

The ValueDistributionAnalyzer class defines this column propery:

```
    @Inject
    @Configured(value = PROPERTY_COLUMN, order = 1)
    @ColumnProperty(escalateToMultipleJobs = true)
    InputColumn<?> _column;
```

Specifically the attribute escalateToMultipleJobs is responsible here. It is a hint to the job builder API that it may build multiple analyzer jobs from one builder which holds a list of columns.

Probably the right thing to do is to ensure that at the time of saving this job builder we only save one <analyzer> element instead of multiple. That way we can reload the job and have a builder instantiated with the same state as before.

**Closed** 2016-01-12 13:53 UTC
Labels: Component: Desktop, Type: Bug
