### ISSUE TITLE
Hidden Property Annotation extension

### ISSUE THREAD

**Issue by khouzvicka** [datacleaner/DataCleaner#716] opened 2015-09-30 11:13 UTC
Hidden Property Annotation is now for hiding specific property from component in gui.
After my improvement, annotation  will have two boolean parameters. One for local hiding (same behavior like before) and second for remote hiding. Programmer can specify hiding for local access or remote access or both.

**Comment by kaspersorensen** [comment] 2015-10-08 09:12
I'm closing this now.

@khouzvicka a little tip: When you post a PR make sure to somewhere in it's description put the text
```
Fixes #716
```
This will ensure that if the PR is merged, then the issue is also closed.

**Closed by kaspersorensen** 2015-10-08 09:12 UTC
Labels: Component: Webapp, Type: Enhancement
