### ISSUE TITLE
CompareFilter with LIKE operator and NullCheckFilter, unexpected results

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1429] opened 2016-07-12 07:03 UTC
In a job with CompareFilter (using LIKE operator for filtering some prefix) and NullCheckFilter, the CompareFilter gives unexpected results. 

LIKE '11%' also returns '211' value. This is strange, in my opinion, itself but I can imagine some prefix like ".*11%" or so in the guts. 

However, the same Datastore & CompareFilter configuration gives "correct" results when the job does not contain NullCheckFilter. 

After discussion with @LosD, problem seems to be in query optimization. Debug output for "simple" case contains expected SQL query with WHERE ... LIKE '11%' part. 

Complex case does not contain any SQL with WHERE in it. 

COMPLEX CASE:
![complex](https://cloud.githubusercontent.com/assets/13213915/16757842/9b252608-480e-11e6-965f-57552cf5655c.png)

SIMPLE CASE:
![simple](https://cloud.githubusercontent.com/assets/13213915/16757844/9b2af628-480e-11e6-8aaa-cc73e96b1f2d.png)

**Comment by LosD** [comment] 2016-07-12 07:08
This can be reproduced for the simple case if using a non-optimizable datastore like CSV. Issue seems to be in the MetaModel FilterItem/WildcardPattern. It seems like it is not anchored to the beginning of the tested string.

**Comment by LosD** [comment] 2016-08-08 09:55
Fixed by apache/metamodel#115

**Closed by LosD** 2016-08-08 09:55 UTC
Labels: Component: Desktop, Type: Bug
