### ISSUE TITLE
Recreating analyzer renderers in the result screen

### ISSUE THREAD

**Issue by stefanjanssen** [datacleaner/DataCleaner#964] opened 2015-11-26 09:59 UTC
As reported by @Jan-Arie , switching tabs in the result screen seems to recreate the analyzer renderer. For most analyzers this is not a problem, but for the deduplication it is. The training tool has to redo the entire setup processing after switching to the progress information for even a second. This can easily take over 10 minutes on a larger reference / data sample.

**Comment by kaspersorensen** [comment] 2015-12-10 12:27
Hmm I cannot reproduce this on a normal AnalyzerResult (tried adding some System.out.println(...) stuff in a standard swing renderer - it only puts it once).

Maybe it's specific to the way the result of the renderer works? I will dig around a bit more ...

**Comment by kaspersorensen** [comment] 2015-12-10 12:32
Closing this as the issue was discovered to be specific to the extension used here.

**Closed by kaspersorensen** 2015-12-10 12:32 UTC
Labels: Component: Desktop, Type: Bug
