### ISSUE TITLE
Edit Table Lookup / Insert causes not responding DC 

### ISSUE THREAD

**Issue by markansink** [datacleaner/DataCleaner#872] opened 2015-11-02 08:47 UTC
When I add a table lookup (SQL server or postgress) to a job I can configure this without any issue. But when I try to edit this DC freezes and the only way to exit DC is to kill the application.

This freeze also occurs on the write to table and update table components.

DataCleaner version is 4.5 and 4.5.1

**Comment by markansink** [comment] 2015-11-02 08:54
If I don't kill DC it the configuration panel will be shown after 5 minutes.

**Comment by kaspersorensen** [comment] 2015-11-02 20:58
Can you give some idea of content on this database your looking into. Especially number of schemas and tables? I have a hunch that maybe the time is spent in some ineffecient loops around discovering metadata. But just a hunch (because we previously saw similar issues on database with 100s of schemas and tables etc.)

**Comment by markansink** [comment] 2015-11-03 06:33
It even occurs when I use a csv file in the lookup component. So this has 1 schema and 1 table. 
My database I used at first had 1 schema with 40+ tables.

**Comment by kaspersorensen** [comment] 2015-11-03 10:04
I cannot reproduce myself. Can we schedule a call where you can demonstrate this to myself or Dennis or Claudia?

**Comment by markansink** [comment] 2015-11-05 14:13
We can schedule a call tomorrow so I can demonstrate this

**Comment by kaspersorensen** [comment] 2015-11-19 18:00
We could not reproduce this anymore. Closing it for now, but feel free to reopen @markansink if you encounter it again.

**Closed by kaspersorensen** 2015-11-19 18:00 UTC
Labels: Component: Desktop, Type: Bug
