### ISSUE TITLE
Grouper component: Could not detect next consumer in processing order

### ISSUE THREAD

**Issue by jhorcicka** [datacleaner/DataCleaner#1420] opened 2016-07-01 12:02 UTC
While trying to simulate "group by sql query" I ran into this issue. Is it a bug or a wrong configuration? 

![grouper1](https://cloud.githubusercontent.com/assets/13213915/16521027/5959e8b2-3f94-11e6-9309-5e28730fc314.png)
![grouper2](https://cloud.githubusercontent.com/assets/13213915/16521028/595b1a70-3f94-11e6-9ab1-662db9d34d5f.png)
![grouper-error](https://cloud.githubusercontent.com/assets/13213915/16521029/595def20-3f94-11e6-9d60-373b3952997b.png)

**Comment by kaspersorensen** [comment] 2016-07-01 15:13
That would seem like a bug. Any way you can reproduce (maybe using orderdb) and share the .analysis.xml file?

**Comment by jhorcicka** [comment] 2016-07-04 07:29
Hmm, today it works like a charm. Same job, same configuration. I tried that with both orderdb and "my oracle database". The only difference I can think of (apart from constellation of stars) is the database state but that does not seem related. 

I think you can close this issue, @kaspersorensen.

**Comment by kaspersorensen** [comment] 2016-07-04 18:23
OK I will close it, although I think you should also be able to do that since you reported it. I just gave my 5c :)

**Closed by kaspersorensen** 2016-07-04 18:23 UTC
Labels: Component: Desktop, Type: Bug
