### ISSUE TITLE
Check for available updates

### ISSUE THREAD

**Issue by manuelvandenberg** [datacleaner/DataCleaner#1338] opened 2016-05-13 13:19 UTC
DataCleaner could automatically check for new updates on startup and notify the user if there is a newer version available.
This message could be displayed on startup in interactive mode.
DC Monitor could do the same and display a non-intrusive notification for admin users.

**Comment by kaspersorensen** [comment] 2016-05-17 03:41
Duplicate of / related to #1009

**Comment by LosD** [comment] 2016-05-18 12:20
Let's close this one, then.

**Closed by LosD** 2016-05-18 12:20 UTC
